const USER_STATUS = {
    ENABLED: 'ENABLED',
    PENDING: 'PEDING',
    NOT_AUTHORIZED: 'NOT_AUTHORIZED'
}

const EMPLOYEE_ROLE = {
    COMMON: 'COMMON',
    ADMIN: 'ADMIN'
}

module.exports = {
    USER_STATUS,
    EMPLOYEE_ROLE
}